import {useCallback, useEffect, useRef, useState, type ReactNode} from 'react';
import {api, collectionLabels, collectionSelection, hasActiveCollection, numberedCollections, collectionCaption, type Collection, type Project} from './model';
import ProjectCard from './ProjectCard';
import Browser from './Browser';
import Materials from './Materials';
import ProjectForm from './ProjectForm';
import {Commits, Documents, CommitDetail, DocumentDetail} from './Evidence';
import {useData, type FileNode} from './data';
import {Icon, Modal, Pagination, PageCount, Text, MemoFields, date, message, deltaText, type Confirm} from './ui';

type Screen = 'projects' | 'dashboard' | 'collections' | 'commits' | 'documents' | 'materials' | 'files' | 'settings' | 'add' | 'commit' | 'document';
interface Overview {selected: {counts: Record<'commits' | 'files' | 'documents', number | null>}; previous: {counts: Record<'commits' | 'files' | 'documents', number | null>} | null; delta: Record<'commits' | 'files' | 'documents', number | null>}
const names: Record<Screen,string> = {projects:'등록된 프로젝트 목록',dashboard:'대시보드',collections:'수집 기록',commits:'커밋',documents:'개발 문서',materials:'사용자 추가 자료',files:'수집 당시 프로젝트 구조',settings:'프로젝트 설정',add:'프로젝트 추가',commit:'커밋 상세',document:'문서 상세'};
function CollectionsTable({records, selected, move, edit, remove}: {records: Collection[]; selected: string; move: (c: Collection) => void; edit: (c: Collection) => void; remove: (c: Collection) => void}) {
  return <div className="table-scroll"><table className="collections-table"><thead><tr><th>번호</th><th>제목</th><th>설명</th><th>브랜치</th><th>수집 시각</th><th>작업</th></tr></thead><tbody>{records.map(c => <tr key={c.id} className={c.id === selected ? 'selected-row' : ''}><td>#{c.number}</td><td><Text text={c.title || '—'}/></td><td><Text text={c.description || '—'}/></td><td><Text text={c.snapshot.branch ?? '미확보'}/></td><td>{date(c.snapshot.started_at ?? c.created_at)}</td><td><div className="actions"><span className="move-slot">{c.id === selected ? <span className="badge current">현재 선택됨</span> : <button onClick={() => move(c)}>이 수집으로 이동</button>}</span><button onClick={() => edit(c)}>수정</button><button className="danger" onClick={() => remove(c)}>삭제</button></div></td></tr>)}</tbody></table>{!records.length && <p className="hint">완료된 수집 기록이 없습니다.</p>}</div>;
}
function SelectedRecord({collection, edit, structure}: {collection: Collection; edit: () => void; structure:()=>void}) {
  const ref = useRef<HTMLParagraphElement>(null), [more,setMore] = useState(false);
  useEffect(() => {const node = ref.current; if (!node) return; const measure = () => setMore(node.scrollHeight > node.clientHeight + 1); const resize = new ResizeObserver(measure); resize.observe(node); measure(); return () => resize.disconnect();}, [collection.description]);
  return <section className="card selected-collection"><div className="selected-record-layout"><div className="selected-record-fields"><h2>선택된 수집 기록</h2><dl><dt>수집한 브랜치:</dt><dd><Text text={collection.snapshot.branch ?? '미확보'}/></dd><dt>제목:</dt><dd><Text text={collection.title || '제목 없음'}/></dd><dt>설명:</dt><dd><div className="description"><p ref={ref} className="two-lines">{collection.description || '설명 없음'}</p>{more && <details className="description-popover" onKeyDown={e=>{if(e.key==='Escape')e.currentTarget.open=false;}}><summary>더보기⌄</summary><div role="region" aria-label="전체 수집 설명" tabIndex={0}>{collection.description}</div></details>}</div></dd><dt>수집 시각:</dt><dd>{date(collection.snapshot.started_at ?? collection.created_at)}</dd></dl></div><div className="record-buttons"><button onClick={edit}><Icon name="edit"/> 편집</button><button className="structure-button" onClick={structure}><Icon name="folder"/> 프로젝트 구조 보기</button></div></div>{collection.state!=='completed' && <p className="notice">{collectionLabels[collection.state]}. 아직 완료 기록이 아닙니다.</p>}</section>;
}
export default function App() {
  const [projects,setProjects] = useState<Project[]>([]), [project,setProject] = useState<Project | null>(null), [selected,setSelected] = useState('');
  const [screen,setScreen] = useState<Screen>('projects'), [origin,setOrigin] = useState<Screen>('dashboard'), [oid,setOid] = useState(''), [document,setDocument] = useState<FileNode | null>(null);
  const [switcher,setSwitcher] = useState(false), [search,setSearch] = useState(''), [error,setError] = useState(''), [toast,setToast] = useState(''), [busy,setBusy] = useState(false), [dirty,setDirty] = useState(false), [revision,setRevision] = useState(0), [collectionPage,setCollectionPage] = useState(1);
  const [confirmation,setConfirmation] = useState<{title:string; content:ReactNode; action:() => Promise<void> | void; dismissOnStart?:boolean; error?:string; busy?:boolean} | null>(null);
  const [memo,setMemo] = useState<{id:string; title:string; description:string; confirming:boolean; initial?:boolean; busy?:boolean; error?:string} | null>(null);
  const [completedMemo,setCompletedMemo] = useState<{project:string; collection:Collection} | null>(null);
  const [deletion,setDeletion]=useState<{project:Project; name:string; busy?:boolean; error?:string} | null>(null);
  const deletedProjects=useRef(new Set<string>());
  const selections=useRef<Record<string,{selected:string;page:number;scroll:Record<string,number>}>>({});
  const switcherRef = useRef<HTMLDivElement>(null);
  useEffect(()=>{if(!switcher)return;const outside=(e:PointerEvent)=>{if(!switcherRef.current?.contains(e.target as Node))setSwitcher(false);};const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')setSwitcher(false);};window.addEventListener('pointerdown',outside);window.addEventListener('keydown',escape);return()=>{window.removeEventListener('pointerdown',outside);window.removeEventListener('keydown',escape);};},[switcher]);
  const projectId = useRef(''), request = useRef<AbortController | null>(null), loading = useRef(false), scroll = useRef<Record<string,number>>({});
  const tracked = useRef<{project:string; id:string; cancel:boolean; at:number; initialMemo?:boolean} | null>(null);
  const toastTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const notify = useCallback((text:string) => {if(toastTimer.current) clearTimeout(toastTimer.current); setToast(text); toastTimer.current = setTimeout(() => setToast(''), 4000);}, []);
  const load = useCallback(async () => {
    if (loading.current) return; loading.current = true;
    const abort = new AbortController(); request.current = abort; const started = Date.now();
    try {
      const response = await api<Project[]>('projects','GET',undefined,abort.signal); if (abort.signal.aborted) return; const list=response.filter(p=>!deletedProjects.current.has(p.id));setProjects(list);
      const target = projectId.current; if (!target) {setProject(null); return;}
      if(!list.some(p=>p.id===target)){projectId.current='';setProject(null);setSelected('');setScreen('projects');setOid('');setDocument(null);delete selections.current[target];return;}
      const p = await api<Project>(`projects/${target}`,'GET',undefined,abort.signal); if (abort.signal.aborted || target !== projectId.current) return;
      p.collections = numberedCollections(p.collections ?? []);
      setProject(p); setSelected(old => collectionSelection(p.collections ?? [], old));
      const pending = tracked.current;
      if (pending?.project === target && started >= pending.at) {
        const c = p.collections?.find(c => c.id === pending.id);
        if (c?.state === 'completed') {notify('수집이 완료됐습니다.'); tracked.current = null; setRevision(n => n+1); if(pending.initialMemo && !pending.cancel) setCompletedMemo({project:target,collection:c});}
        else if (!c) {pending.initialMemo=false; if(!p.collection_busy) {if (pending.cancel) notify('수집 취소 정리가 완료됐습니다.'); else setError('수집 완료 기록을 확인하지 못했습니다. 미완료 자료가 정리됐거나 기록이 삭제됐을 수 있습니다.'); tracked.current = null;}}
        else if (!['capturing','queued','running'].includes(c.state)) {pending.initialMemo=false; if(c.state==='cancel_pending') pending.cancel=true;}
      }
    } catch(e) {if(!abort.signal.aborted) setError(message(e));} finally {if(request.current === abort) loading.current = false;}
  }, [notify]);
  useEffect(() => {void load(); const interval = setInterval(() => void load(), 1200); return () => {clearInterval(interval); request.current?.abort(); if(toastTimer.current) clearTimeout(toastTimer.current);};}, [load]);
  const confirm: Confirm = (title,content,action,dismissOnStart=false) => setConfirmation({title,content,action,dismissOnStart});
  const active = project?.collections?.find(c => ['capturing','queued','running','cancel_pending'].includes(c.state));
  const collection = project?.collections?.find(c => c.id === selected);
  const completed = project?.collections?.filter(c => c.state === 'completed') ?? [];
  const overview = useData<Overview>(collection ? `collections/${collection.id}/overview` : null, `${collection?.state}:${revision}:${completed.map(c=>c.id).join(',')}`);
  useEffect(() => {setCollectionPage(p => Math.min(p, Math.max(1,Math.ceil(completed.length/10))));}, [completed.length]);
  useEffect(() => {if(active && !tracked.current) tracked.current = {project:projectId.current,id:active.id,cancel:active.state === 'cancel_pending',at:Date.now()};}, [active]);
  useEffect(() => {
    if(!completedMemo) return;
    if(completedMemo.project!==project?.id){setCompletedMemo(null);return;}
    if(memo || confirmation) return;
    const c=completedMemo.collection;
    setCompletedMemo(null); setMemo({id:c.id,title:c.title ?? '',description:c.description ?? '',confirming:false,initial:true});
  },[completedMemo,project?.id,memo,confirmation]);
  const navigate = (next:Screen, action?:() => void) => {
    const go = () => {scroll.current[screen] = window.scrollY;
      if(next==='projects'){if(projectId.current)selections.current[projectId.current]={selected,page:collectionPage,scroll:{...scroll.current}};request.current?.abort();loading.current=false;projectId.current='';setProject(null);setSelected('');setOid('');setDocument(null);setSearch('');}
      action?.(); setScreen(next); setSwitcher(false); requestAnimationFrame(() => window.scrollTo(0,scroll.current[next] ?? 0));};
    if (dirty) confirm('저장하지 않은 변경사항', '입력한 변경사항을 저장하지 않고 이동하시겠습니까?', () => {setDirty(false); go();}); else go();
  };
  const switchProject = (p:Project, destination:Screen='dashboard') => {if(p.id===projectId.current){navigate(destination);return;}navigate(destination, () => {const freshEntry=!projectId.current;if(projectId.current)selections.current[projectId.current]={selected,page:collectionPage,scroll:{...scroll.current}};request.current?.abort(); loading.current=false; projectId.current=p.id; setProject(p); const previous=selections.current[p.id];setSelected(freshEntry ? '' : previous?.selected ?? ''); setError(''); tracked.current=null; scroll.current=previous?.scroll ?? {}; setCollectionPage(previous?.page ?? 1); setOid('');setDocument(null);void load();});};
  const openCommit = (id:string) => {if(screen !== 'commit') setOrigin(screen); setOid(id); navigate('commit');};
  const openDocument = (f:FileNode) => {setOrigin(screen); setDocument(f); navigate('document');};
  const move = (c:Collection) => confirm('수집 기록 이동', '정말 이 수집 기록으로 이동하시겠습니까?', () => {setSelected(c.id); setRevision(n=>n+1); navigate('dashboard');});
  const edit = (c:Collection) => setMemo({id:c.id,title:c.title ?? '',description:c.description ?? '',confirming:false});
  const remove = (c:Collection) => confirm('수집 기록 삭제', '이 수집 기록과 해당 기록에만 연결된 자료를 영구 삭제합니다. 복구할 수 없습니다. 프로젝트·다른 수집·사용자 추가 자료·원본 Repository는 유지됩니다.', async () => {await api(`collections/${c.id}`,'DELETE'); setRevision(n=>n+1); await load(); notify('삭제가 완료되었습니다.');});
  const start = () => {if(!project || busy) return; const pid=project.id; confirm('지금 수집', '현재 프로젝트의 자료를 수집하시겠습니까?', async () => {setBusy(true); setError(''); try {const c = await api<Collection | null>(`projects/${pid}/collections`,'POST'); if (!c) throw new Error('자료 확보에 실패했습니다. 완료 기록은 생성되지 않았으며 미완료 자료를 정리합니다.'); if(projectId.current===pid) {tracked.current={project:pid,id:c.id,cancel:false,at:Date.now(),initialMemo:true}; setSelected(c.id);} await load();} finally {setBusy(false);}},true);};
  const cancel = () => {if(!active || !project) return; const c=active, pid=project.id; confirm('수집 취소', '진행 중인 수집을 취소하고 미완료 자료를 정리하시겠습니까? 기존 완료 기록과 사용자 추가 자료는 유지됩니다.', async () => {if(projectId.current===pid) tracked.current={project:pid,id:c.id,cancel:true,at:Date.now()}; setCompletedMemo(current=>current?.collection.id===c.id?null:current); await api(`collections/${c.id}/cancel`,'POST'); await load();});};
  const baseScreen = screen === 'commit' || screen === 'document' ? origin : screen;
  const detail = screen === 'commit' || screen === 'document';
  const previousSelection = useRef(selected);
  useEffect(() => {if(previousSelection.current !== selected && detail) {setScreen('dashboard'); setDocument(null); setOid('');} previousSelection.current = selected;}, [selected, detail]);
  const allTable = (recent:boolean) => <section className="card"><header><h2>{recent ? '최근 수집 기록' : '전체 수집 기록'}</h2>{recent ? <button onClick={() => navigate('collections')}>전체 보기 →</button> : <PageCount page={collectionPage} total={completed.length}/>}</header><p className="hint">‘이 수집으로 이동’ 버튼을 클릭하면 해당 수집 시점의 자료로 이동할 수 있습니다.</p><CollectionsTable records={recent ? completed.slice(0,5) : completed.slice((collectionPage-1)*10,collectionPage*10)} selected={selected} move={move} edit={edit} remove={remove}/>{!recent && <Pagination page={collectionPage} total={completed.length} change={setCollectionPage}/>}</section>;
  const hierarchy:Screen[] = detail ? ['dashboard',screen==='commit'?'commits':'documents',screen] : ['collections','commits','documents','materials','files'].includes(screen) ? ['dashboard',screen] : [screen];
  return <div className="app-shell"><aside className="sidebar">
    <button className="brand" onClick={()=>navigate('projects')}>PROJECT LOG</button><p>개발의 흔적을 체계적으로.</p>
    <div ref={switcherRef}><button className="project-switch" aria-label={`프로젝트 선택: ${project?.name ?? '없음'}`} aria-expanded={switcher} onClick={() => setSwitcher(!switcher)}><Icon name="folder"/><Text text={project?.name ?? '프로젝트 선택'}/>⌄</button>{switcher && <div className="project-menu"><input aria-label="프로젝트 검색" placeholder="프로젝트 이름 검색" value={search} onChange={e => setSearch(e.target.value)}/>{projects.filter(p=>p.name.toLocaleLowerCase().includes(search.toLocaleLowerCase())).map(p=><button key={p.id} aria-current={p.id===project?.id ? 'true' : undefined} onClick={()=>switchProject(p)}><Text text={p.name}/>{p.id===project?.id && <span><Icon name="check"/> 선택됨</span>}</button>)}<button onClick={()=>navigate('add')}>＋ 프로젝트 추가</button></div>}</div>
    <nav><button disabled={!project} className={screen==='dashboard'?'active':''} onClick={()=>navigate('dashboard')}><Icon name="home"/> 대시보드</button><button disabled={!project} className={screen==='settings'?'active':''} onClick={()=>navigate('settings')}><Icon name="settings"/> 프로젝트 설정</button></nav>
    <div className="sidebar-foot"><p className="quality-note">ⓘ 수집 자료의 양과 품질에 따라 향후 생성되는 결과물의 품질이 달라질 수 있습니다.</p><small>Local Project Log · v0.1.0</small></div>
    </aside><main>
    <div className="sticky-top"><nav className="breadcrumbs" aria-label="Breadcrumb">{project && screen!=='projects' && screen!=='add' && <><Text text={project.name}/><span>›</span></>}{hierarchy.map((item,i)=><span className="crumb" key={item}>{i>0 && <span>› </span>}{i===hierarchy.length-1 ? <Text text={item==='document' ? document?.name ?? '문서' : names[item]}/> : <button onClick={()=>navigate(item)}>{names[item]}</button>}</span>)}</nav>
    {screen==='dashboard' && project && <header className="project-header"><h1><span className="project-symbol"><Icon name="folder"/></span><Text text={project.name}/></h1><button className="primary" disabled={busy || (!active && !project.base_branch) || (hasActiveCollection(project) && (!active || active.state==='cancel_pending'))} onClick={active ? cancel : start}><Icon name={active?'stop':'play'}/>{busy ? '수집 요청 중…' : active?.state==='cancel_pending' ? '취소 정리 중' : active ? '수집 취소' : project.collection_busy ? '실패 자료 정리 중' : '지금 수집'}</button></header>}</div>
    {error && <div className="alert" role="alert">{error}<button onClick={()=>setError('')}>닫기</button></div>}{screen==='dashboard' && project && !project.base_branch && <p className="notice">기본 브랜치가 미설정입니다. 프로젝트 설정에서 수집 기준 브랜치를 지정하세요. 기존 자료 조회는 유지됩니다.</p>}{screen==='dashboard' && project?.collection_busy && !active && <p className="notice" role="status">실패 또는 중단된 수집 자료를 정리하는 중입니다. 완료 기록으로 표시하지 않습니다.</p>}{toast && <div className="toast" role="status">{toast}</div>}
    {(detail || screen==='files') && <button className="back-button" onClick={()=>navigate(screen==='files'?'dashboard':origin)}>← {names[screen==='files'?'dashboard':origin]}{screen==='commit' && origin==='commits'?'으로':'로'} 돌아가기</button>}
    <div hidden={detail}>
    {baseScreen==='projects' && <section className="projects-page"><header><h1>등록된 프로젝트 목록</h1><button className="primary" onClick={()=>navigate('add')}>＋ 프로젝트 추가</button></header>{!projects.length && <section className="card"><h2>등록된 프로젝트가 없습니다.</h2><p>프로젝트 추가로 로컬 Git Repository를 등록하세요.</p></section>}<div className="project-grid">{projects.map(p=><ProjectCard key={p.id} project={p} open={()=>switchProject(p)} edit={()=>switchProject(p,'settings')} remove={()=>setDeletion({project:p,name:''})}/>)}</div></section>}
    {baseScreen==='add' && <ProjectForm key="add" confirm={confirm} dirty={setDirty} saved={()=>{}} created={(p,c,failure)=>{projectId.current=p.id;setProject({...p,collections:numberedCollections(p.collections ?? [])});setSelected(c?.id ?? '');setScreen('dashboard');tracked.current=c?{project:p.id,id:c.id,cancel:false,at:Date.now(),initialMemo:true}:null;if(failure)setError(failure);else notify('프로젝트 등록과 첫 수집 요청이 접수됐습니다.');void load();}}/>}
    {baseScreen==='settings' && project && <ProjectForm key={project.id} project={project} confirm={confirm} dirty={setDirty} saved={p=>{setProject({...p,collections:numberedCollections(p.collections ?? [])});notify('프로젝트 설정을 저장했습니다.');void load();}} created={()=>{}}/>}
    {!project && !['add','projects'].includes(baseScreen) && <section className="card"><h2>프로젝트를 선택하세요.</h2><button onClick={()=>navigate('projects')}>등록된 프로젝트 목록</button></section>}
    {project && <>
      {baseScreen==='dashboard' && <><div className="dashboard-top"><div>{collection ? <SelectedRecord collection={collection} edit={()=>edit(collection)} structure={()=>navigate('files')}/> : <section className="card"><h2>선택된 수집 기록 없음</h2><p>지금 수집으로 자료를 확보하세요.</p></section>}<div className="stats">{(['commits','files','documents'] as const).map((key,i)=><section className={`card stat stat-${key}`} key={key}><span className="stat-icon"><Icon name={(['branch','file','book'] as const)[i]}/></span><div><h3>{['버전 관리 기록','프로젝트 파일','개발 문서'][i]}</h3><strong>{overview.data ? overview.data.selected.counts[key] ?? '미확보' : '—'}</strong>{overview.data?.selected.counts[key]!=null && ' 개'}<p>이전 대비 <b className={(overview.data?.delta[key] ?? 0)>0?'positive':(overview.data?.delta[key] ?? 0)<0?'negative':''}>{overview.data ? deltaText(overview.data.selected.counts[key],overview.data.previous?.counts[key],overview.data.delta[key],!!overview.data.previous) : overview.error ? '조회 실패' : '조회 중'}</b></p></div></section>)}</div>{overview.error && <p role="alert">{overview.error}</p>}{collection && overview.data && (!overview.data.previous || Object.values(overview.data.delta).includes(null)) && <p className="hint">-: 이전 완료 수집 없음. 비교 불가: 현재 또는 이전 수집의 확보 범위를 확정할 수 없음. 현재 남아 있는 직전 완료 수집과 비교합니다.</p>}</div><section className="card project-info"><h2>프로젝트 정보</h2><dl className="info"><dt><Icon name="folder"/>프로젝트 이름</dt><dd><Text text={project.name}/></dd><dt><Icon name="clip"/>프로젝트 경로</dt><dd><Text text={project.path}/><button aria-label="프로젝트 경로 복사" onClick={()=>void navigator.clipboard.writeText(project.path).then(()=>notify('경로를 복사했습니다.')).catch(()=>setError('경로를 복사하지 못했습니다.'))}><Icon name="copy"/></button></dd><dt><Icon name="branch"/>기본 브랜치</dt><dd><Text text={project.base_branch ?? '미설정'}/></dd><dt><Icon name="calendar"/>등록일</dt><dd>{date(project.created_at)}</dd><dt><Icon name="file"/>최근 수집</dt><dd>{date(completed[0]?.snapshot.started_at ?? completed[0]?.created_at)}</dd></dl></section></div>{allTable(true)}{collection && <Commits key={`commits:${collection.id}`} collection={collection} compact all={()=>navigate('commits')} open={c=>openCommit(c.oid)}/>}<div className="two-columns">{collection ? <Documents key={`docs:${collection.id}`} collection={collection} compact all={()=>navigate('documents')} open={openDocument}/> : <section className="card"><h2>개발 문서</h2><p>선택된 수집 기록이 없습니다.</p></section>}<Materials key={project.id} projectId={project.id} compact onAll={()=>navigate('materials')} confirm={confirm} notify={notify}/></div></>}
      {baseScreen==='collections' && allTable(false)}
      {(['commits','documents','files'] as Screen[]).includes(baseScreen) && <p className="collection-basis">{baseScreen==='files'?'선택한 수집 기록:':'자료를 확보한 수집 기록:'} <Text text={collection ? collectionCaption(collection) : '선택 없음'}/></p>}
      {baseScreen==='commits' && collection && <Commits key={collection.id} collection={collection} open={c=>openCommit(c.oid)}/>}
      {baseScreen==='documents' && collection && <Documents key={collection.id} collection={collection} open={openDocument}/>}
      {baseScreen==='materials' && <Materials key={project.id} projectId={project.id} confirm={confirm} notify={notify}/>}
      {baseScreen==='files' && collection && <section className="card"><h2>수집 당시 프로젝트 구조</h2><Browser key={collection.id} collection={collection}/></section>}
    </>}
    </div>
    {screen==='commit' && collection && <CommitDetail key={`${collection.id}:${oid}`} collection={collection} oid={oid} parent={openCommit} notify={notify}/>}
    {screen==='document' && collection && document && <DocumentDetail key={`${collection.id}:${document.path_b64}`} collection={collection} file={document}/>}
    {deletion && <Modal title="프로젝트 영구 삭제" close={()=>setDeletion(null)} busy={deletion.busy}><h3><Text text={deletion.project.name}/></h3><p>이 프로젝트의 등록 정보, 모든 수집 기록·보존 근거와 사용자 추가 자료의 보관 사본을 영구 삭제합니다. 복구 기능이 없습니다.</p><p className="notice">실제 Git Repository 폴더와 원본 파일, 다른 프로젝트의 자료 및 기존 백업은 삭제하지 않습니다.</p><label>삭제할 프로젝트명을 다시 입력하세요.<input aria-label="삭제 확인 프로젝트명" autoComplete="off" value={deletion.name} disabled={deletion.busy} onChange={e=>setDeletion({...deletion,name:e.target.value})}/></label>{deletion.error && <p className="alert" role="alert">{deletion.error}</p>}<footer><button disabled={deletion.busy} onClick={()=>setDeletion(null)}>취소</button><button className="danger" disabled={deletion.busy || deletion.name!==deletion.project.name} onClick={()=>{const d=deletion;setDeletion({...d,busy:true,error:''});void api(`projects/${d.project.id}`,'DELETE',{name:d.name}).then(async()=>{deletedProjects.current.add(d.project.id);delete selections.current[d.project.id];setProjects(old=>old.filter(p=>p.id!==d.project.id));if(projectId.current===d.project.id){projectId.current='';setProject(null);setSelected('');setOid('');setDocument(null);setScreen('projects');}setDeletion(null);await load();notify('삭제가 완료되었습니다.');}).catch(e=>setDeletion({...d,busy:false,error:message(e)}));}}>{deletion.busy?'삭제 중…':'영구 삭제'}</button></footer></Modal>}
    {confirmation && <Modal title={confirmation.title} close={()=>setConfirmation(null)} busy={confirmation.busy}>{confirmation.content}{confirmation.error && <p className="alert" role="alert">{confirmation.error}</p>}<footer><button disabled={confirmation.busy} onClick={()=>setConfirmation(null)}>취소</button><button className="primary" disabled={confirmation.busy} onClick={()=>{const c=confirmation;setConfirmation(c.dismissOnStart ? null : {...c,busy:true,error:''});void Promise.resolve().then(c.action).then(()=>{if(!c.dismissOnStart)setConfirmation(null);}).catch(e=>{if(c.dismissOnStart)setError(message(e));else setConfirmation({...c,busy:false,error:message(e)});});}}>{confirmation.busy?'처리 중…':'확인'}</button></footer></Modal>}
    {memo && !confirmation && <Modal title={memo.initial?'수집 기록 제목·설명 입력':'수집 기록 제목·설명 편집'} close={()=>{if(memo.confirming)setMemo({...memo,confirming:false});else setMemo(null);}} busy={memo.busy}>{memo.initial && <p className="hint">선택 입력입니다. 건너뛰거나 닫아도 이미 시작한 수집을 취소하지 않습니다.</p>}{memo.confirming ? <><p>입력한 제목·설명을 저장하시겠습니까?</p><h3>{memo.title || '제목 없음'}</h3><p className="preserve-lines">{memo.description || '설명 없음'}</p></> : <MemoFields title={memo.title} description={memo.description} change={(title,description)=>setMemo({...memo,title,description})}/>}{memo.error && <p role="alert" className="alert">{memo.error}</p>}<footer><button disabled={memo.busy} onClick={()=>memo.confirming ? setMemo({...memo,confirming:false}) : setMemo(null)}>{memo.initial && !memo.confirming ? '건너뛰기' : '취소'}</button><button className="primary" disabled={memo.busy || Array.from(memo.title).length>50 || Array.from(memo.description).length>200} onClick={()=>{if(!memo.confirming){setMemo({...memo,confirming:true,error:''});return;}const m=memo;setMemo({...m,busy:true,error:''});void api(`collections/${m.id}`,'PATCH',{title:m.title || null,description:m.description || null}).then(async()=>{setMemo(null);await load();notify('수집 기록을 수정했습니다.');}).catch(e=>setMemo({...m,busy:false,error:message(e)}));}}>{memo.busy?'저장 중…':memo.confirming?'확인':'저장'}</button></footer></Modal>}
    </main></div>;
}
